version: '3.6'
services:
  mbtileserver:
    image: consbio/mbtileserver:latest
    restart: always # dev: unless-stopped
    volumes:
      - ../../tiles:/tilesets

  renderer:
    image: consbio/mbgl-renderer:latest
    restart: always
    volumes:
      - ../../tiles:/app/tiles

  api:
    build:
      context: ../..
      dockerfile: docker/api/Dockerfile
    restart: always
    env_file:
      - .env
    command:
      [
        '/usr/local/bin/gunicorn',
        '-k',
        'uvicorn.workers.UvicornWorker',
        '--name',
        'uvicorn',
        '-b',
        ':5000',
        'api.api:app',
      ]
    volumes:
      - ../../data:/home/app/data # TODO: this can originate from location in staging config
      - ../../api:/home/app/api # main API
      - ../../analysis:/home/app/analysis # needed for analysis utils
      - ../../constants:/home/app/constants # needed for JSON files for blueprint, indicators
    ports:
      - '5000:5000'

  worker:
    build:
      context: ../..
      dockerfile: docker/api/Dockerfile
    restart: always
    env_file:
      - .env
    command: ['/usr/local/bin/arq', 'api.worker.WorkerSettings']
    volumes:
      - ../../data:/home/app/data # TODO: this can originate from location in staging config
      - ../../api:/home/app/api # main API
      - ../../analysis:/home/app/analysis # needed for analysis utils
      - ../../constants:/home/app/constants # needed for JSON files for blueprint, indicators
      - ../../examples:/home/app/examples # DEBUG ONLY
      - ../../tests:/home/app/tests # DEBUG ONLY

  redis:
    image: 'redis:alpine'
    restart: always

  caddy:
    image: caddy/caddy:2.1.1-alpine
    depends_on:
      - 'mbtileserver'
    restart: always
    ports:
      - '8080:80'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_certs:/root/.caddy
      - ../../ui/public:/var/www

volumes:
  caddy_certs:
