version: '3.6'
services:
  sa-api:
    build:
      context: ../..
      dockerfile: docker/api/Dockerfile
    restart: always
    external_links:
      - redis
    env_file:
      - .env
    command:
      [
        '/usr/local/bin/gunicorn',
        '-k',
        'uvicorn.workers.UvicornWorker',
        '--name',
        'uvicorn',
        '-b',
        ':5000',
        'api.api:app',
      ]
    volumes:
      - user_upload:/tmp/sa-reports
      - /data:/home/app/data
      - ../../api:/home/app/api # main API
      - ../../analysis:/home/app/analysis # needed for analysis utils
      - ../../constants:/home/app/constants # needed for JSON files for blueprint, indicators
    ports:
      - '5000:5000'
    logging:
      driver: journald
    networks:
      - shared

  sa-worker:
    build:
      context: ../..
      dockerfile: docker/api/Dockerfile
    restart: always
    external_links:
      - redis
      - renderer
    env_file:
      - .env
    command: ['/usr/local/bin/arq', 'api.worker.WorkerSettings']
    volumes:
      - user_upload:/tmp/sa-reports
      - /data/sa:/home/app/data
      - ../../api:/home/app/api # main API
      - ../../analysis:/home/app/analysis # needed for analysis utils
      - ../../constants:/home/app/constants # needed for JSON files for blueprint, indicators
    logging:
      driver: journald
    networks:
      - shared

networks:
  shared:
    driver: bridge
    name: shared

volumes:
  caddy_certs:
  user_upload:
