version: "3.7"

services:
  sa-ui-build:
    build:
      context: ../..
      dockerfile: docker/ui/Dockerfile
    image: ${DOCKER_REGISTRY}/sa-ui-build:latest
    entrypoint: gatsby
    volumes:
      - "./:/app"
      - /app/node_modules
    network_mode: "host"
