version: "3.6"
services:
  redis:
    image: ${DOCKER_REGISTRY}/redis:6.0.9-alpine
    logging:
      driver: journald
    networks:
      - shared

  mbtileserver:
    image: ${DOCKER_REGISTRY}/mbtileserver:latest
    restart: always
    volumes:
      - /data/tiles:/tilesets
    logging:
      driver: journald
    networks:
      - shared

  renderer:
    image: ${DOCKER_REGISTRY}/mbgl-renderer:latest
    restart: always
    volumes:
      - /data/tiles:/app/tiles
    logging:
      driver: journald
    networks:
      - shared

  caddy:
    image: ${DOCKER_REGISTRY}/caddy:2.2.1-alpine
    depends_on:
      - mbtileserver
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_certs:/data
      - caddy_config:/config
      - /var/www:/var/www
    logging:
      driver: journald
    networks:
      - shared

networks:
  shared:
    driver: bridge
    name: shared

volumes:
  caddy_certs:
  caddy_config:
